### ISSUE TITLE
Problems with ESLint engine

### ISSUE THREAD

**Issue by expl0r3r** [tagview/arcanist-extensions#14]
Greetings,

Many thanks for this repo, has helped my team streamline a lot of our work.
And with the recent addition of the ESLint engine we were more than excited to update our arc-extensions.

But after updating and setting it as per instructions,

I always get an output like this,

` OKAY  No lint warnings.`

I went ahead to debug the php source and found out that changing this,
```
public function willLintPaths(array $paths) {
    $this->checkEslintInstallation();
    $this->execution = new ExecFuture('eslint --format=json --no-color ' . implode($paths, ' '));
  }
```

to this,
```
public function willLintPaths(array $paths) {
    $this->checkEslintInstallation();
    // print_r('eslint --format=json --no-color ' . implode($paths, ' '));
    $this->execution = new ExecFuture('eslint --format=json --no-color ' . implode($paths, ' '));
    $this->didRunLinters();
  }
```

solved it.

**Comment by expl0r3r** [comment]
Another notable thing,

OS: xubuntu 16.04
PHP:
```
PHP 7.0.4-7ubuntu2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by reu** [comment]
Thanks a lot @expl0r3r!

**Comment by reu** [comment]
Landed: https://github.com/tagview/arcanist-extensions/commit/bd2463671edf8b8b385c095b27a5ebeef7466a5d
