### ISSUE TITLE
Failed to load TapTestEngine

### ISSUE THREAD

**Issue by elsigh** [tagview/arcanist-extensions#4]
From my .arcconfig

...
  "load": [
    "arcanist-extensions/multi_test_engine",
    "arcanist-extensions/tap_test_engine"
  ],

  "unit.engine": "MultiTestEngine",

  "unit.engine.multi-test.engines": [
    {
      "engine": "TapTestEngine",
      "unit.engine.tap.command": "grunt app-tests"
    }
  ]
}

If I change it to 

"engine": "TAPTestEngine"

things work fine.

**Comment by reu** [comment]
Looks like it is a documentation bug, I will take a look.

**Comment by reu** [comment]
Fixed: acd35556a2f4bdcf2a4a77fb495aa200e6462559
Thanks for the report!
